### PR TITLE
Feature/15 onboarding screen UI

### LINKED ISSUE #15: Onboarding Screen UI
# REQUIREMENTS
Create an Unboarding screen design. 

# DESIGN
The provided design are only references or an example of how the onboarding screens should look like.
image
image
image

# Acceptance Criteria
List all required acceptance criteria
- [x] Has to describe the steps
- [x] Important to combine the colours as they are provided.

### PR DESCRIPTION
**Pull request by Ing-Heber**
# Description
What did you implemented/Why did you implemented this:
 - I created three screens files that for now will show how the On Boarding screens should look like based on issue #15 design.
 - It was designed and coded in order to start looking for components like the screen indicator in OnBoardScreenConect and OnBoardScreenCall (Will be implemented soon in sprint 2 after adding the react-navigation)
 - I also fixed some small details in the color file and implemented in the readme screens.
 
 # Testing
1. Download my branch (feature/15-Onboarding-Screen-UI).
2. Go to "tribomobile" folder.
3. If you do not see the modules : npm install.
3.  npx react-native start.
4. npx react-native run-android
5. You will se as default the OnBoardScreenConect in the app, if you want to see the others just change their import name like "OnBoardScreenCall" or "OnBoardScreenReceive".

##Screenshots:
-------------------------------------------------- Resulted Design -------------------------------------------------- 
image
image
image

### CODE REVIEW

**Review by develiasdaniel — DISMISSED** [review]
Nice design

**Review by JordiGN — DISMISSED** [review]

**Review by tovl1 — DISMISSED** [review]

**Review by Ocosmee — DISMISSED** [review]
Good job

**Review by OswaldoPineda — DISMISSED** [review]

**Review by alcamk — DISMISSED** [review]
Good job!

**Review by JordiGN — DISMISSED** [review]
Nice men, I see you changed some color names, let's just wait for the definition of the ones proposed by the Rails Team

**Review by tovl1 — DISMISSED** [review]

**Review by luisarmandodv — DISMISSED** [review]

**Review by OswaldoPineda — DISMISSED** [review]

**Review by alcamk — APPROVED** [review]
Good job!

**Review by JordiGN — APPROVED** [review]

**Review by OswaldoPineda — APPROVED** [review]

**Review by tovl1 — APPROVED** [review]

**Pull request merged**
