### PR TITLE
Feature/38 create button component

### LINKED ISSUE #38: Create a button component
# REQUIREMENTS
Create a button component 

# DESIGN
image

# Acceptance Criteria
- [x] Must be same size as the provided example.
- [x] Icon and text must be a prop.
- [x] Has to acomplish three states (normal, disabled and error)

### PR DESCRIPTION
**Pull request by develiasdaniel**
# Description
What did you implemented/Why did you implemented this:
 - I added a test file that shows the different types of cutomized buttons
 - I designed a custom button in small, medium, large sizes
 - I added a prop to add an icon to it
 - I added a prop that activates deactivates the buttonalong.
 
 Examples:
 - What?: I have added a button that is customizable in color, size, and icon. Includes a prop that activates deactivates the button
 - Why?: The buttons are occupied throughout the screens, and only change in size, color
 
 # Testing
- `git clone https://github.com/BrightCoders-Proyectos/tribo-mobile/tree/feature/38-CreateButtonComponent`
- `npm install`
- `npm react-native run-android`
 
 Example:
 - import as follow
`import {CustomButton, ConfigBtnCustom} from './components/CustomButton';`
 - The buttons are implemented as follows
 ```
<CustomButton
        size={ConfigBtnCustom.SIZE.SMALL}
        titleSize={ConfigBtnCustom.TITLE_SIZE.SMALL}
        bgBtn={ConfigBtnCustom.COLOR.GREEN}
        borderColorBtn={ConfigBtnCustom.COLOR.GREEN}
        titleColor={ConfigBtnCustom.COLOR.WHITE}
        widthBtn={ConfigBtnCustom.WIDTH.SMALL}
        title={'Button'}
        disabled={isActive}
 />
```

  ## Screenshots 
- you should be able to do these buttons, purple button deactivates / activates buttons 3 and 6
image

### CODE REVIEW

**Review by JordiGN — APPROVED** [review]
Amazing job, very well done and the design looks exactly as the design document, congrats

**Review by Ing-Heber — APPROVED** [review]
Well done Danny!

**Review by tovl1 — APPROVED** [review]
Good!

**Review by fernandoamz — CHANGES_REQUESTED** [review]
Add the snapshoots testing

**Pull request merged**
