### PR TITLE
Feature/login screen

### PR DESCRIPTION
**Pull request by develiasdaniel**
# Description
What did you implemented/Why did you implemented this:
 - create login screen
 - reuse previously created components
 - error handling view
 
 Examples:
 - What?: I have made the view of the login screen, and your view in case your password or email is incorrect
 - Why?: Is one of the main screens for users
 
 # Testing

 
 Example:
- login
image

- handle error
  
image

  ## Screenshots 
If applicable, include screenshots of the results or screenshots that help to see changes

### CODE REVIEW

**Review by Ing-Heber — APPROVED** [review]

**Comment by alcamk** [comment]
Great job Daniel

**Comment by alcamk** [comment]
Great job!

**Review by alcamk — APPROVED** [review]
Great job!

**Review by JordiGN — APPROVED** [review]
Cool man, very quick and nice! Good job

**Pull request merged**
