### PR TITLE
Feature/36 title component

### PR DESCRIPTION
**Pull request by Ing-Heber**
# Description
What did you implemented/Why did you implemented this:
 - I created a Title component that analyzes its property and displays 3 types of title (screenTitle, formTitle and inputTitle) in order to solve issue #36 so we can now display the titlesText using the Title component style. (As you may see in other issues I did not implemented on each file yet because we will refactor the code and will also apply the provided screens design https://www.figma.com/file/IGRyLwNFX0GKXkikAfzfKw/Tribo?node-id=18%3A2 )
 
 # Testing
 1. Switch to my branch ( feature/36-title-component)
 2. npm install
 3. import my component on WelcomeScreenGuest image
 4. Comment from line 29 to 44, add my component image

 Example:
  - I added the three types of components on WelcomeGuestScreen so you can see them.
  
  ## Screenshots 

image
image
image

(It may look a little bit different because of the google font type and style)

### CODE REVIEW

**Review by develiasdaniel — APPROVED** [review]
good job

**Review by JordiGN — APPROVED** [review]
The documentation is outstanding, excellent job as always!

**Review by tovl1 — APPROVED** [review]
Good job

**Review by luisarmandodv — APPROVED** [review]

**Review by alcamk — APPROVED** [review]
Good job!

**Pull request merged**
